export enum ActionTypes {
  LOGIN_AUTH = 'LOGIN_AUTH',
  SET_NEW_RELEASES = 'SET_NEW_RELEASES',
  SET_EDITOR_PICKS = 'SET_EDITOR_PICKS',
  SET_PLAYLIST = 'SET_PLAYLIST',
  SET_SELECTED_PLAYLIST = 'SET_SELECTED_PLAYLIST',
  SET_SELECTED_TRACK = 'SET_SELECTED_TRACK',
  SET_PLAYLIST_TRACKS = 'SET_PLAYLIST_TRACKS',
  ADD_PLAYLIST_TRACKS = 'ADD_PLAYLIST_TRACKS',
  SET_TRACK_MENU = 'SET_TRACK_MENU',
  RESET_TRACK_MENU = 'RESET_TRACK_MENU'
}
