export enum ActionTypes {
  LOGIN_AUTH = 'LOGIN_AUTH',
  SET_NEW_RELEASES = 'SET_NEW_RELEASES',
  SET_EDITOR_PICKS = 'SET_EDITOR_PICKS',
  SET_PLAYLIST = 'SET_PLAYLIST',
  SET_CURRENT_TRACKS = 'SET_CURRENT_TRACKS',
  ADD_TO_CURRENT_TRACKS = 'ADD_TO_CURRENT_TRACKS',
  SET_PLAYLIST_ID = 'SET_PLAYLIST_ID',
  SET_CURRENTLY_PLAYING = 'SET_CURRENTLY_PLAYING'
}
